version: 2.1
runners:
  runner1:
    config-id: 2
  runner2:
    config-id: 3
jobs:
  catalyst:
    steps:
      - echo "Hello"
      - catalyst deploy appsail --name express --build-path ./ --stack node18 --command "node index.js" -p 16501000000013022
stages:
  - name: build
    runner: runner2
    jobs:
      - catalyst
pipeline-runner: runner1
